export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_REGISTER_SUCCESS = "USER_REGISTER";
export const USER_REGISTER_FAILURE = "USER_REGISTER";
export const USER_GOOGLE_LOGIN = "USER_GOOGLE_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";